version: 2

models:
- name: dim_listings_cleansed
  description: Cleansed table which contains Airbnb listings.
  columns:

  - name: listing_id
    description: Primary key for the listing

  - name: host_id
    description: The hosts's id. References the host table.

  - name: room_type
    description: Type of the apartment / room

  - name: minimum_nights
    description: minimum_nights

- name: dim_hosts_cleansed
  columns:
  - name: host_id

  - name: host_name

  - name: is_superhost

- name: fct_reviews
  columns:
  - name: listing_id

  - name: reviewer_name

  - name: review_sentiment
